from werkzeug.routing import Rule, Map

from txplaya import controllers

url_map = Map([
    Rule('/stream',
         endpoint=controllers.Stream),
    Rule('/playlist', defaults={'action': 'getData'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/insert/<int:position>/<path:filepath>', defaults={'action': 'insert'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/insert/<path:filepath>', defaults={'action': 'insert'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/remove/<int:position>', defaults={'action': 'remove'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/move/<int:start>/<int:end>', defaults={'action': 'move'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/clear', defaults={'action': 'clear'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/library/insert/<int:position>/<string:trackIds>',
         defaults={'action': 'libraryInsert'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/library/insert/<string:trackIds>',
         defaults={'action': 'libraryInsert'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/save/<string:playlistName>', defaults={'action': 'save'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/load/<string:playlistName>', defaults={'action': 'load'},
         endpoint=controllers.PlaylistManager),
    Rule('/playlist/delete/<string:playlistName>', defaults={'action': 'delete'},
         endpoint=controllers.PlaylistManager),
    Rule('/player/start/<int:position>', defaults={'action': 'start'},
         endpoint=controllers.Player),
    Rule('/player/start', defaults={'action': 'start'},
         endpoint=controllers.Player),
    Rule('/player/next', defaults={'action': 'next'},
         endpoint=controllers.Player),
    Rule('/player/prev', defaults={'action': 'prev'},
         endpoint=controllers.Player),
    Rule('/player/stop', defaults={'action': 'stop'},
         endpoint=controllers.Player),
    Rule('/player/pause', defaults={'action': 'pause'},
         endpoint=controllers.Player),
    Rule('/library', defaults={'action': 'getLibrary'},
         endpoint=controllers.Library),
    Rule('/library/rescan', defaults={'action': 'rescan'},
         endpoint=controllers.Library),
    Rule('/infostream',
         endpoint=controllers.InfoStream)
])
